description: A website with a blog
header_text: Brookes Dream Blog
footer_text: Copyright 2020 Your name
header_feature_image: /uploads/pages.jpg
gridlayout: false
items:
  - name: Editor
    siteurl: /admin/
    tab: true
logo: /uploads/face.jpg
upzoom: true
favicon: /uploads/favicon.ico
title: Your name or name of site
