title: Chris Jennings Blog for Brookes
description: This web site os a sample for my students
header_feature_image: ../uploads/49078305272_9001a1d84a_3k.jpg
items:
  - name: Editor
    siteurl: /admin/
    tab: true
logo: /uploads/face.jpg
header_text: Brookes Dream Blog
footer_text: Copyright 2020 Chris Jennings
gridlayout: false
upzoom: true
favicon: /uploads/favicon.ico
